#!/bin/bash


#BATCH --nodes=1                   # the number of nodes you want to reserve
#SBATCH --ntasks-per-node=1         # the number of tasks/processes per node
#SBATCH --cpus-per-task=2          # the number cpus per task
#SBATCH --partition=normal         # on which partition to submit the job
#SBATCH --mem=4G                   # total memory per node (copied from https://researchcomputing.princeton.edu/support/knowledge-base/memory
#SBATCH --time=0:20:00             # the max wallclock time (time limit your job will run)

#SBATCH --job-name=Bcftools     # the name of your job
#SBATCH --mail-type=ALL             # receive an email when your job starts, finishes normally or is aborted
#SBATCH --mail-user=apicella@uni-muenster.de # your mail address

# LOAD MODULES HERE IF REQUIRED
module load palma/2022a GCC/11.3.0 BCFtools/1.15.1


# START THE APPLICATION
cd /scratch/tmp/apicella/projects/wormsQC/dmx/Runs_109_cycles/3_gatk_HaplotypeCaller/Merged_clean_runs/14_VariantRecal_15_ApplyVQSR/

bash ./bcftools_tbi_index.sh
